spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_TYPE}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: 'true'

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  time:
    accessTime: ${JWT_ACCESS_TIME}
    refreshTime: ${JWT_REFRESH_TIME}

gauth:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  redirectUri: ${REDIRECT_URI}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    s3:
      bucket: ${AWS_BUCKET_NAME}
      url: ${AWS_URL}
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error