spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_TYPE}
    generate-ddl: true

  main:
    allow-bean-definition-overriding: 'true'

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
